name: Publish Docker image

on:
  push:
    branches:
      - master
      - development
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push MusicBrainz image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: telix5000/musicbrainz-all-in-one:latest
          provenance: true
          sbom: true
